name: "CI-PR"

on:
  workflow_call:
  merge_group:
  pull_request:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  verify:
    name: Verify-Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "22"
          cache: "maven"

      - name: Install Dependencies
        run: mvn -B install -DskipTests -f pom.xml

      - name: Verify
        run: mvn -B verify -f pom.xml

  format:
    name: Format-Spotless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "22"
          cache: "maven"

      - name: Check formatting
        run: mvn -B spotless:check -f pom.xml

  test:
    name: Test-Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "22"
          cache: "maven"

      - name: Install Dependencies
        run: mvn -B install -DskipTests -f pom.xml

      - name: Test
        run: mvn -B test -f pom.xml

  lint:
    name: Lint-Qodana
    runs-on: ubuntu-latest
    needs:
      - verify
      - format
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.1
        with:
          pr-mode: false
          args: --apply-fixes,--config,.github/qodana.yaml
          push-fixes: pull-request
          post-pr-comment: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Qodana SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json

  analyze:
    name: Analyze-CodeQL
    runs-on: ubuntu-latest
    needs:
      - verify
      - format
      - test
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin
          build-mode: none # Only Java is analyzed
          queries: security-and-quality

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java-kotlin"
