name: "CI-PR"

on:
  workflow_call:
  merge_group:
  pull_request:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  verify:
    name: Run Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "22"
          cache: "maven"

      - name: Verify
        run: mvn -B verify -f pom.xml

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "22"
          cache: "maven"

      - name: Test
        run: mvn -B test -f pom.xml

  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "22"
          cache: "maven"
          cache-dependency-path: "pom.xml" # Creates a cache for spotless only

      - name: Check formatting
        run: mvn -B spotless:check -f pom.xml

  analyze-qodana:
    name: Analyze Qodana
    runs-on: ubuntu-latest
    if: github.event_name != 'merge_group'
    needs:
      - verify
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.1
        with:
          pr-mode: true
          args: --config,.github/qodana.yaml
          post-pr-comment: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Qodana SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
