name: "CI"

on:
  workflow_call:
  merge_group:
  pull_request:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  verify:
    name: Verify-Maven
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: chitchat/setup-java@v1

      - name: Verify
        run: mvn verify -f pom.xml

  format:
    name: Format-Spotless
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: chitchat/setup-java@v1

      - name: Check formatting
        run: mvn spotless:check -f pom.xml

  lint:
    name: Lint-Qodana
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.1
        with:
          pr-mode: true
          args: --apply-fixes
          push-fixes: pull-request
          post-pr-comment: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  test:
    name: Test-Maven
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: chitchat/setup-java@v1

      - name: Test
        run: mvn test -f pom.xml

  analyze:
    name: Analyze-CodeQL
    runs-on: ubuntu-latest
    needs:
      - verify
      - format
      - lint
      - test
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin
          build-mode: none # Only Java is analyzed
          queries: security-and-quality

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java-kotlin"
