on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  analyze-qodana:
    name: Analyze-Qodana
    runs-on: ubuntu-latest
    needs:
      - verify
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.1
        with:
          pr-mode: false
          args: --apply-fixes,--config,.github/qodana.yaml
          push-fixes: pull-request
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Qodana SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json

  analyze-codeql:
    name: Analyze-CodeQL
    runs-on: ubuntu-latest
    needs:
      - verify
      - test
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin
          build-mode: none # Only Java is analyzed
          queries: security-and-quality

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java-kotlin"